services:
  snack-hub-order-app:
    image: ghcr.io/team-one-pos-tech/snack-hub-order-service:latest
    container_name: snack-hub-order-app
    networks:
      - snack-hub-network
    depends_on:
      - rabbitmq
      - snack-hub-db
    ports:
      - "5688:8080"

  snack-hub-payment-app:
    image: ghcr.io/team-one-pos-tech/snackhubpaymentapi:latest
    container_name: snack-hub-payment-app
    networks:
      - snack-hub-network
    depends_on:
      - rabbitmq
      - snack-hub-db
    ports:
      - "5588:8080"

  snack-hub-client-app:
    image: ghcr.io/team-one-pos-tech/snack-hub-client-service:latest
    container_name: snack-hub-client-app
    networks:
      - snack-hub-network
    depends_on:
      - rabbitmq
      - snack-hub-db
    ports:
      - "5488:8080"

  snack-hub-product-app:
    image: ghcr.io/team-one-pos-tech/snack-hub-product-service:latest
    container_name: snack-hub-product-app
    networks:
      - snack-hub-network
    depends_on:
      - rabbitmq
      - snack-hub-db
    ports:
      - "5388:8080"
      
  snack-hub-production-app:
    image: ghcr.io/team-one-pos-tech/snack-hub-production:latest
    container_name: snack-hub-production-app
    networks:
      - snack-hub-network
    depends_on:
      - rabbitmq
      - snack-hub-db
    ports:
      - "5288:8080"

  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: rabbitmq
    ports:
       - "5672:5672"
       - "15672:15672"
    networks:
       - snack-hub-network

  snack-hub-db:
    image: postgres:latest
    container_name: snack-hub-db
    ports:
      - "5432:5432"
    networks:
      - snack-hub-network
    volumes:
      - snack-hub-db:/var/lib/postgresql/data

  snack-hub-mongodb:
    image: mongo
    container_name: snack-hub-mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - "27017:27017"

volumes:
  snack-hub-db:

networks:
  snack-hub-network:
    driver: bridge