services:
  snack-hub-order-app:
    environment:
        RabbitMQ__Host: rabbitmq
        RabbitMQ__User: guest
        RabbitMQ__Password: guest
        Storage__MongoDb__ConnectionString: mongodb://admin:admin@snack-hub-mongodb:27017/
        Storage__MongoDb__Database: snack-hub-order
        ASPNETCORE_ENVIRONMENT: Development
        ASPNETCORE_HTTP_PORTS: 8080

  snack-hub-payment-app:
    environment:
        RabbitMQ__Host: rabbitmq
        RabbitMQ__User: guest
        RabbitMQ__Password: guest
        Storage__PostgreSQL__Host: snack-hub-db
        Storage__PostgreSQL__User: postgres
        Storage__PostgreSQL__Password: postgres
        Storage__PostgreSQL__Database: snack-hub-payment
        ApiGateway__MercadoPagoEndpoint: https://api.mercadopago.com
        ASPNETCORE_ENVIRONMENT: Development
        ASPNETCORE_HTTP_PORTS: 8080

  snack-hub-client-app:
    environment:
        RabbitMQ__Host: rabbitmq
        RabbitMQ__User: guest
        RabbitMQ__Password: guest
        Storage__PostgreSQL__Host: snack-hub-db
        Storage__PostgreSQL__User: postgres
        Storage__PostgreSQL__Password: postgres
        Storage__PostgreSQL__Database: snack-hub-client
        ASPNETCORE_ENVIRONMENT: Development
        ASPNETCORE_HTTP_PORTS: 8080

  snack-hub-product-app:
    environment:
        RabbitMQ__Host: rabbitmq
        RabbitMQ__User: guest
        RabbitMQ__Password: guest
        Storage__MongoDb__ConnectionString: mongodb://admin:admin@snack-hub-mongodb:27017/
        Storage__MongoDb__Database: snack-hub-product
        ASPNETCORE_ENVIRONMENT: Development
        ASPNETCORE_HTTP_PORTS: 8080

  snack-hub-production-app:
    environment:
        RabbitMQ__Host: rabbitmq
        RabbitMQ__User: guest
        RabbitMQ__Password: guest
        Storage__PostgreSQL__Host: snack-hub-db
        Storage__PostgreSQL__User: postgres
        Storage__PostgreSQL__Password: postgres
        Storage__PostgreSQL__Database: snack-hub-production
        ASPNETCORE_ENVIRONMENT: Development
        ASPNETCORE_HTTP_PORTS: 8080

  snack-hub-gateway-app:
    environment:
        ASPNETCORE_ENVIRONMENT: Development
        ASPNETCORE_HTTP_PORTS: 8080
        ORDER-CLUSTER__DESTINATIONS__DOCKER-COMPOSE__ADDRESS: snack-hub-order-app:5688
        PAYMENT-CLUSTER__DESTINATIONS__DOCKER-COMPOSE__ADDRESS: snack-hub-payment-app:5588
        CLIENT-CLUSTER__DESTINATIONS__DOCKER-COMPOSE__ADDRESS: snack-hub-client-app:5488
        PRODUCT-CLUSTER__DESTINATIONS__DOCKER-COMPOSE__ADDRESS: snack-hub-product-app:5388
        PRODUCTION-CLUSTER__DESTINATIONS__DOCKER-COMPOSE__ADDRESS: snack-hub-production-app:5288

        
  snack-hub-db:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres