services:
  snackhub.production.app:
    image: ghcr.io/team-one-pos-tech/snack-hub-production:latest
    container_name: snack-hub-production-app
    networks:
      - snack-hub-network
    depends_on:
      - rabbitmq
    ports:
      - "5288:8080"

  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: rabbitmq
    ports:
       - "5672:5672"
       - "15672:15672"
    networks:
       - snack-hub-network

  snack-hub-production-db:
    image: postgres:latest
    container_name: snack-hub-production-db
    ports:
      - "5432:5432"
    networks:
      - snack-hub-network
    volumes:
      - snack-hub-production-db:/var/lib/postgresql/data