services:
  snackhub.production.app:
    environment:
        RabbitMQ__Host: rabbitmq
        RabbitMQ__User: guest
        RabbitMQ__Password: guest
        Storage__PostgreSQL__Host: snack-hub-production-db
        Storage__PostgreSQL__User: postgres
        Storage__PostgreSQL__Password: postgres
        Storage__PostgreSQL__Database: SnackHub-ProductionService
        ASPNETCORE_ENVIRONMENT: Development
        ASPNETCORE_HTTP_PORTS: 8080
    ports:
      - "5288:8080"
