services:
  snack-hub-client-app:
    environment:
        RabbitMQ__Host: rabbitmq
        RabbitMQ__User: guest
        RabbitMQ__Password: guest
        Storage__PostgreSQL__Host: snack-hub-db
        Storage__PostgreSQL__User: postgres
        Storage__PostgreSQL__Password: postgres
        Storage__PostgreSQL__Database: snack-hub-client
        ASPNETCORE_ENVIRONMENT: Development
        ASPNETCORE_HTTP_PORTS: 8080

  snack-hub-product-app:
    environment:
        RabbitMQ__Host: rabbitmq
        RabbitMQ__User: guest
        RabbitMQ__Password: guest
        Storage__PostgreSQL__Host: snack-hub-db
        Storage__PostgreSQL__User: postgres
        Storage__PostgreSQL__Password: postgres
        Storage__PostgreSQL__Database: snack-hub-product
        ASPNETCORE_ENVIRONMENT: Development
        ASPNETCORE_HTTP_PORTS: 8080

  snack-hub-production-app:
    environment:
        RabbitMQ__Host: rabbitmq
        RabbitMQ__User: guest
        RabbitMQ__Password: guest
        Storage__PostgreSQL__Host: snack-hub-db
        Storage__PostgreSQL__User: postgres
        Storage__PostgreSQL__Password: postgres
        Storage__PostgreSQL__Database: snack-hub-production
        ASPNETCORE_ENVIRONMENT: Development
        ASPNETCORE_HTTP_PORTS: 8080

  snack-hub-db:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres