services:
  snack-hub-order-app:
    image: ghcr.io/team-one-pos-tech/snack-hub-order-service:latest
    container_name: snack-hub-order-app
    restart: always
    networks:
      - snack-hub-network
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - "5688:8080"

  snack-hub-payment-app:
    image: ghcr.io/team-one-pos-tech/snack-hub-payment-service:latest
    container_name: snack-hub-payment-app
    restart: always
    networks:
      - snack-hub-network
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - "5588:8080"

  snack-hub-client-app:
    image: ghcr.io/team-one-pos-tech/snack-hub-client-service:latest
    container_name: snack-hub-client-app
    restart: always
    networks:
      - snack-hub-network
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - "5488:8080"

  snack-hub-product-app:
    image: ghcr.io/team-one-pos-tech/snack-hub-product-service:latest
    container_name: snack-hub-product-app
    restart: always
    networks:
      - snack-hub-network
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - "5388:8080"
      
  snack-hub-production-app:
    image: ghcr.io/team-one-pos-tech/snack-hub-production:latest
    container_name: snack-hub-production-app
    restart: always
    networks:
      - snack-hub-network
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - "5288:8080"

  snack-hub-gateway-app:
    image: ghcr.io/team-one-pos-tech/snack-hub-gateway:latest
    container_name: snack-hub-gateway-app
    restart: always
    networks:
      - snack-hub-network
    links:
      - snack-hub-order-app
      - snack-hub-payment-app
      - snack-hub-client-app
      - snack-hub-product-app
      - snack-hub-production-app
    ports:
      - "5188:8080"

  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: rabbitmq
    restart: always
    ports:
       - "5672:5672"
       - "15672:15672"
    networks:
       - snack-hub-network
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5

  snack-hub-db:
    image: postgres:latest
    container_name: snack-hub-db
    restart: always
    ports:
      - "5432:5432"
    networks:
      - snack-hub-network
    volumes:
      - snack-hub-db:/var/lib/postgresql/data

  snack-hub-mongodb:
    image: mongo
    container_name: snack-hub-mongodb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - "27017:27017"
    networks:
      - snack-hub-network
    volumes:
      - snack-hub-mongodb:/data/db

volumes:
  snack-hub-db:
  snack-hub-mongodb:

networks:
  snack-hub-network:
    driver: bridge