@GatewayHostAddress = http://localhost:5188
@GatewayPath = order-api


### Better insert by consuming the ProductionOrderSubmittedRequest event from OrderService

// Create Orders
POST {{GatewayHostAddress}}/{{GatewayPath}}/
Content-Type: application/json
Accept: application/json

{
  "clientId": "{client-id}",
  "items": [
    {
      "productId": "b04d4264-cc63-4cb0-851d-981bd34aa725",
      "quantity": 3
    },
    {
      "productId": "a869d0bc-fccb-4d4c-8b5a-38840d50b6e8",
      "quantity": 1
    }
  ]
}

###

// List all Orders - no filters
GET {{GatewayHostAddress}}/{{GatewayPath}}
Content-Type: application/json
Accept: application/json

###

// List Order Payment Status
GET {{GatewayHostAddress}}/{{GatewayPath}}/{order-id}/payment-status
Content-Type: application/json
Accept: application/json

###

// Get Order By Id
GET {{GatewayHostAddress}}/{{GatewayPath}}/{order-id}
Content-Type: application/json
Accept: application/json

###

PUT {{GatewayHostAddress}}/{{GatewayPath}}/Cancel
Content-Type: application/json
Accept: application/json

{
  "orderId": "{order-id}"
}