### Should be executed to get data inserted by auth file

@GatewayHostAddress = http://localhost:5005
@GatewayPath = client-api

GET {{GatewayHostAddress}}/{{GatewayPath}}/client-api/{client-cpf}
Content-Type: application/json
Accept: application/json

###

GET {{GatewayHostAddress}}/{{GatewayPath}}/client-api/{client-id}
Content-Type: application/json
Accept: application/json

####
