@GatewayHostAddress = http://localhost:5005
@GatewayPath = order-api


### Better insert by consuming the ProductionOrderSubmittedRequest event from OrderService

// Create Orders
POST {{GatewayHostAddress}}/{{GatewayPath}}/Confirm
Content-Type: application/json
Accept: application/json

{
  "clientId": "{client-id}",
  "items": [
    {
      "productId": "{product-id}",
      "quantity": 2
    }
  ]
}

###

// List all Orders - no filters
GET {{GatewayHostAddress}}/{{GatewayPath}}
Content-Type: application/json
Accept: application/json

###

// List Order Payment Status
GET {{GatewayHostAddress}}/{{GatewayPath}}/{order-id}/payment-status
Content-Type: application/json
Accept: application/json

###

PUT {{GatewayHostAddress}}/{{GatewayPath}}/Cancel
Content-Type: application/json
Accept: application/json

{
  "orderId": "{order-id}"
}

####
