@GatewayHostAddress = http://localhost:5188
@GatewayPath = production-api

// List all Production Orders - no filters
GET {{GatewayHostAddress}}/{{GatewayPath}}/GetAllProductionOrders
Content-Type: application/json
Accept: application/json
###

PUT {{GatewayHostAddress}}/{{GatewayPath}}/UpdateStatus
Content-Type: application/json
Accept: application/json

{
  "id": "{production-order-id}"
}
####
// ProductionOrderStatus.Received => ProductionOrderStatus.Preparing,
// ProductionOrderStatus.Preparing => ProductionOrderStatus.Done,
// ProductionOrderStatus.Done => ProductionOrderStatus.Finished,

####


### Better insert by consuming the ProductionOrderSubmittedRequest event from OrderService

// Create Production Orders - Better only consume Order and Payment service
POST {{GatewayHostAddress}}/{{GatewayPath}}/CreateProductionOrder
Content-Type: application/json
Accept: application/json

// Where {Order id} is a order from Order Service

{
  "orderId": "{Order Id}",
  "items": [
    {
      "productId": "{product-id}",
      "quantity": 2
    }
  ]
}

###