@GatewayHostAddress = http://localhost:5688
@GatewayPath = product-api

POST {{GatewayHostAddress}}/{{GatewayPath}}
Content-Type: application/json
Accept: application/json

{
  "name": "X-Abacaxi",
  "category": 0,
  "price": 9.99,
  "description": "Trem gostoso demais!"
}

###

POST {{GatewayHostAddress}}/{{GatewayPath}}
Content-Type: application/json
Accept: application/json

{
  "name": "Coca-Cola",
  "category": 2,
  "price": 7.45,
  "description": "Coca geladinha!"
}

###

#Get Products by category
GET {{GatewayHostAddress}}/{{GatewayPath}}/0
Content-Type: application/json
Accept: application/json

###

#Get products by Id
GET {{GatewayHostAddress}}/{{GatewayPath}}/{Product Id}
Content-Type: application/json
Accept: application/json

###

#List all products
GET {{GatewayHostAddress}}/{{GatewayPath}}
Content-Type: application/json
Accept: application/json

###

#Delete products by Id
DELETE {{GatewayHostAddress}}/{{GatewayPath}}/{Product Id}
Content-Type: application/json
Accept: application/json

###