// Should be executed to get data inserted by auth file

@GatewayHostAddress = http://localhost:5688
@GatewayPath = client-api

###
GET {{GatewayHostAddress}}/{{GatewayPath}}/61189242010
Content-Type: application/json
Accept: application/json

###

GET {{GatewayHostAddress}}/{{GatewayPath}}/{client-id}
Content-Type: application/json
Accept: application/json

####
