on: [push]
jobs:
  build-and-test:
    uses: Team-One-Pos-Tech/SnackHub.SharedWorkFlows/.github/workflows/build.yml@main
    with:
      solution-name: "SnackHub.Api.Gateway.sln"
      api-project-name: "SnackHub.Gateway"
      sonar-project-key: "Team-One-Pos-Tech_SnackHub.ApiGateway"
    secrets:
      sonar-token: ${{secrets.SONAR_TOKEN}}
      
  docker-setup:
    needs: build-and-test
    uses: Team-One-Pos-Tech/SnackHub.SharedWorkFlows/.github/workflows/dockerize.yml@main
    with:
      image-name: "team-one-pos-tech/snack-hub-gateway"
      api-entrypoint-binary: "SnackHub.Gateway.dll"

  Deploy:
    name: "Deploy development"
    runs-on: [self-hosted, vmprod]
    needs: docker-setup
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: '${{ github.actor }}'
          password: '${{ secrets.GITHUB_TOKEN }}'
      
      - name: Docker Compose Down
        run: docker compose down

      - name: Docker system prune
        run: docker system prune --all --force

      - name: Docker Compose Up
        run: docker compose up -d --force-recreate --build
